services:
  - type: web
    name: hms-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hms-postgres
          property: connectionString

      - key: CELERY_BROKER_URL
        fromService:
          name: hms-redis
          type: redis
          property: connectionString

      - key: CELERY_RESULT_BACKEND
        fromService:
          name: hms-redis
          type: redis
          property: connectionString

  - type: worker
    name: hms-celery
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: celery -A worker.celery.celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hms-postgres
          property: connectionString

      - key: CELERY_BROKER_URL
        fromService:
          name: hms-redis
          type: redis
          property: connectionString

      - key: CELERY_RESULT_BACKEND
        fromService:
          name: hms-redis
          type: redis
          property: connectionString

databases:
  - name: hms-postgres
    plan: free
    databaseName: hms
    user: hms_user

  - name: hms-redis
    plan: free
